### ISSUE TITLE
Provide build log file

### ISSUE THREAD

**Issue by emkll** [freedomofpress/kernel-builder#11]
https://github.com/freedomofpress/build-logs contains the build logs for all the production artifacts we release. Given the lack of reproducibility of the builds (#3), we should make it easy for a developer to submit build logs. We could tee the output to a unique file on disk, and have the developer commit that file to https://github.com/freedomofpress/build-logs.

In the meantime, setting the terminal scrollback to infinite and copy-pasting the console output is sufficient as a manual workaround.

**Comment by conorsch** [comment]
This would indeed be grand. We've long wanted support for it https://github.com/freedomofpress/ansible-role-grsecurity-build/issues/53. At least we can do it manually now, as you say. In https://github.com/freedomofpress/build-logs/commit/cdeea2ec9b77e18e0c10b72d9b63ab7648af691e I had to scroll for nearly 10m in order to capture the entirety of terminal output. :upside_down_face:

**Comment by legoktm** [comment]
This was fixed by @cfm in https://github.com/freedomofpress/kernel-builder/pull/39.
