### ISSUE TITLE
Document rebuild process for source offer recipients

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/kernel-builder#22]
For folks receiving a source tarball from FPF, it would be useful to provide clearer instructions here on how to use it and rebuild it with this tooling.

**Comment by creviera** [comment]
Just noting that we recently added instructions about how to add the source tarball to our s3 bucket so that our tooling can provide temporary links and reply to source request emails (see https://github.com/freedomofpress/kernel-builder/pull/21).

I don't think we'll ever need to rebuild the source tarball as part of this process. As far as getting the link, the instructions are in our private tooling repo, so how do you imagine our docs will look for this?

**Comment by zenmonkeykstop** [comment]
I think the context here is not about producing/distributing the tarballs but about what the folks who get them do with them.

Not sure it's actually possible to build from a tarball using this repo tho - the tarball is produced as part of the build process, so if you wanted to do it you'd need to edit out the bits in `build-kernel.sh` that make the tarball, copy the tarball into the container, and run the actual kernel build commands against it.

(This might be a useful feature to add actually.)

**Comment by creviera** [comment]
> I think the context here is not about producing/distributing the tarballs but about what the folks who get them do with them.

Ah, thanks for the clarification.
