### ISSUE TITLE
script/mkdebian changes with 6.6

### ISSUE THREAD

**Issue by thedeadliestcatch** [freedomofpress/kernel-builder#41]
A quick note: beware intdeb-pkg has been removed and also sourcename will fail to be assigned properly, as the Makefile and related files for 6.6 have changed sufficiently to make script/mkdebian incompatible as-is.

**Comment by zenmonkeykstop** [comment]
Thank you! we're on the 5.15 series for now but will need to plan for a move to 6.6 in the near-to-mid future, so this is helpful.

**Comment by zenmonkeykstop** [comment]
Thanks again - it's more of a logistical question than anything else. SecureDrop runs on a bunch of different hardware including stuff we don't know about, so we try to coordinate on major/minor version updates to make the transition relatively seamless.

Our hardware recommendations are due to be updated, and that is often what motivates the major version bump, so this is a great time to be looking at it.

**Comment by zenmonkeykstop** [comment]
We haven't looked at that  yet, be very interested in how it goes.

**Comment by legoktm** [comment]
Thanks for starting this @thedeadliestcatch. I think patching the build script was a nice attempt but in the end seems like it's going to be a bit of a maintenance pain. We can just have a proper debian/ package in this repository and build it after we finish building the kernel package.

Then the only real patch we need is the reproducibility patch, which we should actually try to upstream (#19).

**Comment by legoktm** [comment]
I ended up just porting the mkdebian changes to the 6.6 branch for now because it wasn't too bad (my WIP is https://github.com/freedomofpress/kernel-builder/pull/45). This'll let us get started on builds and testing the new kernels and I can cleanup the packaging in parallel with that.
