### ISSUE TITLE
Support distro strings in changelog

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/kernel-builder#5]
Right now, all builds are marked "unstable": 

```
make clean
sh ./scripts/package/mkdebian
Using default distribution of 'unstable' in the changelog
Install lsb-release or set $KDEB_CHANGELOG_DIST explicitly
```

Use the KDEB_CHANGELOG_DIST var, and/or install lsb-release to use the host os.

**Comment by legoktm** [comment]
In ecf411f52b4c50b04eab5adbab548e34619da990 you added lsb-release, so now the changelog says it's for `buster`, since that's the OS we're using for building. I think it doesn't really matter because we run the kernels on bullseye and focal anyways.

So I'm going to close this as done because it does no longer use "unstable", though I don't really see that as an issue.
